# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=10, verbose_name='\u6635\u79f0')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('content', models.TextField(default=True, help_text='\u8bf7\u6587\u660e\u7559\u8a00,\u9075\u5b88\u76f8\u5173\u6cd5\u5f8b\u6cd5\u89c4!', verbose_name='\u8bc4\u8bba')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('status', models.BooleanField(default=False, verbose_name='\u662f\u5426\u663e\u793a')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Articles', verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u7ba1\u7406',
                'verbose_name_plural': '\u8bc4\u8bba\u7ba1\u7406',
            },
        ),
    ]
