# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('cover_img', models.ImageField(max_length=30, upload_to='uploads/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('content', models.TextField(verbose_name='\u6b63\u6587')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('status', models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u5ba1\u6838'), (3, '\u5220\u9664')], default=1, verbose_name='\u6587\u7ae0\u72b6\u6001')),
                ('is_top', models.IntegerField(choices=[(1, '\u7f6e\u9876'), (2, '\u5206\u7c7b\u7f6e\u9876'), (3, '\u8bdd\u9898\u7f6e\u9876'), (0, '\u4e0d\u7f6e\u9876')], default=0, verbose_name='\u7f6e\u9876')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': '\u6587\u7ae0\u7ba1\u7406',
                'verbose_name_plural': '\u6587\u7ae0\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u79f0')),
                ('cover_img', models.ImageField(max_length=30, upload_to='uploads/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('des', models.CharField(max_length=160, verbose_name='\u63cf\u8ff0')),
                ('keywords', models.CharField(max_length=100, verbose_name='\u5173\u952e\u8bcd')),
                ('status', models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u5ba1\u6838')], default=1, verbose_name='\u680f\u76ee\u72b6\u6001')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('is_nav', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5bfc\u822a')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u4eba')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': '\u5206\u7c7b\u7ba1\u7406',
                'verbose_name_plural': '\u5206\u7c7b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u79f0')),
                ('cover_img', models.ImageField(max_length=30, upload_to='uploads/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('des', models.CharField(max_length=160, verbose_name='\u63cf\u8ff0')),
                ('keywords', models.CharField(max_length=100, verbose_name='\u5173\u952e\u8bcd')),
                ('status', models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u5ba1\u6838')], default=1, verbose_name='\u8bdd\u9898\u72b6\u6001')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('is_nav', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5bfc\u822a')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u4eba')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': '\u8bdd\u9898\u7ba1\u7406',
                'verbose_name_plural': '\u8bdd\u9898\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='articles',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(to='article.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
