# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u94fe\u63a5\u540d\u79f0')),
                ('href', models.URLField(verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('index', models.PositiveIntegerField(default=99, verbose_name='\u6743\u9650')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('is_display', models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u4eba')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': '\u53cb\u60c5\u94fe\u63a5',
                'verbose_name_plural': '\u53cb\u60c5\u94fe\u63a5',
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '\u6700\u65b0\u6587\u7ae0'), (3, '\u6700\u70ed\u6587\u7ae0'), (4, '\u6700\u8fd1\u8bc4\u8bba')], default=1, verbose_name='\u5c55\u793a\u7c7b\u578b')),
                ('content', models.CharField(blank=True, help_text='\u5982\u679c\u8bbe\u7f6e\u7684\u4e0d\u662fHTML\u7c7b\u578b\uff0c\u53ef\u4e3a\u7a7a', max_length=500, verbose_name='\u5185\u5bb9')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('is_display', models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'verbose_name': '\u4fa7\u8fb9\u680f',
                'verbose_name_plural': '\u4fa7\u8fb9\u680f',
            },
        ),
    ]
